### PR TITLE
add option for using a different y matrix

### PR DESCRIPTION
**Pull request by gwaygenomics**
Currently, there are only two options being supported. The default mutation matrix or the one created by `xena` data.

One important thing to consider is that the data was generated by a different script in a [different repository](https://github.com/greenelab/tybalt/blob/master/process_data.ipynb).

There is likely to be future cross talk between the two repositories (and also a third at https://github.com/gwaygenomics/pancan_viz). Is there an optimal way to facilitate this cross-talk?

### CODE REVIEW

**Comment by dhimmel** [comment]
> There is likely to be future cross talk between the two repositories 

What do you mean by cross talk? If it's just data dependencies, use versioned GitHub URLs to read data

**Comment by gwaygenomics** [comment]
> If it's just data dependencies, use versioned GitHub URLs to read data

It is likely to only be data dependencies, yes. Thanks!

**Comment by gwaygenomics** [comment]
I will update this script pointing to a versioned URL once greenelab/tybalt#70 is merged.

**Comment by gwaygenomics** [comment]
Versioned URL not supported with a git LFS file. I will merge this in as is

**Comment by dhimmel** [comment]
> Versioned URL not supported with a git LFS file.

That's not my experience. They hyperlink just like a non-LFS file, IMO.

**Comment by gwaygenomics** [comment]
> That's not my experience. They hyperlink just like a non-LFS file, IMO.

Ah, I was copying the wrong URL. I will update in a new PR shortly

**Pull request merged**
